<?php

namespace Models;

class Team
{
    /**
     * @var string
     */
    private string $id;

    /**
     * @var string
     */
    private string $name;

    // no other properties needed for now

    /**
     * @return string
     */
    public function getId(): string
    {
        return $this->id;
    }
    // only getter needed for now - should be autogenerated by the storage solution

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->getName();
    }

    /**
     * @param string $name
     * @return $this
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}