<?php

namespace Models;

class Team
{
    /**
     * @var int
     */
    private int $id;

    /**
     * @var string
     */
    private string $name;

    // no other properties needed for now

    public function __construct(int $id){
        $this->id = $id;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }
    // only getter needed for now - should be autogenerated by the storage solution

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->getName();
    }

    /**
     * @param string $name
     * @return $this
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}