<?php

namespace Models;

class Team
{
    public const ALLOWED_STATUSES = [
        self::STATUS_AVAILABLE,
        self::STATUS_PLAYING,
    ];

    public const STATUS_AVAILABLE = "available";
    public const STATUS_PLAYING   = "playing";

    /**
     * @var int
     */
    private int $id;

    /**
     * @var string
     */
    private string $name;

    /**
     * @var string
     */
    private string $status;

    // no other properties needed for now

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    // only getter should be needed - should be autogenerated by the storage solution

    /**
     * @param int $id
     * @return $this
     */
    public function setId(int $id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->getName();
    }

    /**
     * @param string $name
     * @return $this
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * @param string $status
     */
    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return $this
     */
    public function startGame()
    {
        return $this->setStatus(self::STATUS_PLAYING);
    }

    /**
     * @return $this
     */
    public function endGame()
    {
        return $this->setStatus(self::STATUS_AVAILABLE);
    }
}